#include<stdio.h>
#include<string.h>
#include<pthread.h>
#include<stdlib.h>
#include<unistd.h>
pthread_ttid[10];
intcounter;
pthread_mutex_tlock=PTHREAD_MUTEX_INITIALIZER;
pthread_cond_tcon=PTHREAD_COND_INITIALIZER;
structpassenger
{
intkey;
structpassenger*next;
};
//Thequeueofpassengers
structStation
{
structpassenger*front,*rear;
};
structpassenger*newNode()
{
structpassenger*temp=(structpassenger*)malloc(sizeof(structpassenger));
temp->next=NULL;
returntemp;
}
//Autilityfunctiontocreateanemptyqueue
structStation*createQueue()
{
structStation*q=(structStation*)malloc(sizeof(structStation));
q->front=q->rear=NULL;
returnq;
}
//Thefunctiontoaddakeyktoq
voidadd(structStation*q)
{
//CreateanewLLnode
structpassenger*temp=newNode();
if(q->rear==NULL)
{
q->front=q->rear=temp;
return;
}
q->rear->next=temp;
q->rear=temp;
}
structtrain
{ intnumber;
intseats;
structStation*q;
};
structpassenger*load(structStation*q)
{
//Ifqueueisempty,returnNULL.
if(q->front==NULL)
returnNULL;
//Storepreviousfrontandmovefrontonenodeahead
structpassenger*temp=q->front;
q->front=q->front->next;
//IffrontbecomesNULL,thenchangerearalsoasNULL
if(q->front==NULL)
q->rear=NULL;
returntemp;
}
void*stationOnBoard(structtrain*q)
{
printf("PassengerLoadeed\n");
printf("\nTrainhasbeenBoarded%d\n",q->number);
pthread_cond_signal(&con);
}
void*trytrain(void*ar)
{
pthread_mutex_lock(&lock);
structtrain*a=(structtrain*)ar;
unsignedlongi=0;
printf("%d\n",a->seats);
printf("\nTrainno.%disonthestationwaitingforpassengers\n",a->number);
pthread_cond_wait(&con,&lock);
while(i<a->seats)
{
sleep(1);
if(load(a->q)!=NULL)
i++;
}pthread_cond_wait(&con,&lock);
stationOnBoard(a);
pthread_mutex_unlock(&lock);
returnNULL;
}
void*stationWaitForTrain(structStation*q)
{
add(q);
printf("\npassengeronstation\n");
}
void*stationLoadTrain(void*a)
{
trytrain(&a);
}
intmain(void)
{
inti=0;
interror;
intc;
intk;
structStation*q=createQueue();
structtraina;
a.q=q;
printf("\t\t\tIndianRail\t\n");
if(pthread_mutex_init(&lock,NULL)!=0)
{
printf("\nmutexinithasfailed\n");
return1;
}
x:
sleep(1);
printf("\tChooseTheActivity:\n1.Passengeronstation\n2.Trainarrivedonstation\n3.
Exit\n");
scanf("%d",&c);
if(c==1){
stationWaitForTrain(q);
}
elseif(c==2)
{
printf("\t\tTrainInfo\t\t\n");
printf("\nEnterthetrainnumber:\n");
scanf("%d",&(a.number));
printf("\nEnterthenumberofseatsinthetrain:\n");
scanf("%d",&(a.seats));
printf("%d",a.seats);
error=pthread_create(&(tid[i]),NULL,&stationLoadTrain,(void*)&a);
if(error!=0)
printf("\nPlatformisnotempty:[%s]",strerror(error));
i++;
if(i==10)
i=0;
}
if(c!=3)
gotox;
for(intj=0;j<10;j++)
pthread_join(tid[j],NULL);
pthread_mutex_destroy(&lock);
pthread_cond_destroy(&con);
return0;
}
